# Generated by Django 4.2.11 on 2024-04-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleproduction',
            name='year',
            field=models.IntegerField(unique=True, verbose_name='年份'),
        ),
    ]
