# Generated by Django 4.2.11 on 2024-04-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_alter_appleproduction_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleEfficiency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50, unique=True, verbose_name='国家')),
                ('efficiency', models.IntegerField(verbose_name='效率')),
            ],
            options={
                'verbose_name': '苹果效率',
                'verbose_name_plural': '苹果效率',
                'db_table': 'tb_apple_efficiency',
            },
        ),
    ]
